FROM ubuntu:latest
LABEL maintainer="rssungjae1@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python python-pip

#docker commit test ubuntu_python
RUN pip install numpy
RUN pip install opencv-python
RUN pip install opencv-contrib-python